//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Http_Post.Res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Http_Post.Res.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Btn_About {
            get {
                return ResourceManager.GetString("Btn_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create event.
        /// </summary>
        public static string Btn_Create {
            get {
                return ResourceManager.GetString("Btn_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by date.
        /// </summary>
        public static string Btn_DateSearch {
            get {
                return ResourceManager.GetString("Btn_DateSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Btn_Events {
            get {
                return ResourceManager.GetString("Btn_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string Btn_LogOut {
            get {
                return ResourceManager.GetString("Btn_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Btn_Settings {
            get {
                return ResourceManager.GetString("Btn_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Theme.
        /// </summary>
        public static string Btn_Theme {
            get {
                return ResourceManager.GetString("Btn_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending date is less than Begining date.
        /// </summary>
        public static string DateError {
            get {
                return ResourceManager.GetString("DateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such events.
        /// </summary>
        public static string DateErrorNoEvents {
            get {
                return ResourceManager.GetString("DateErrorNoEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose dates.
        /// </summary>
        public static string DateSearching {
            get {
                return ResourceManager.GetString("DateSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string DateSearchingBtn {
            get {
                return ResourceManager.GetString("DateSearchingBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No address.
        /// </summary>
        public static string NoAddressError {
            get {
                return ResourceManager.GetString("NoAddressError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No begin time.
        /// </summary>
        public static string NoBeginTime {
            get {
                return ResourceManager.GetString("NoBeginTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No description.
        /// </summary>
        public static string NoDescriptionError {
            get {
                return ResourceManager.GetString("NoDescriptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No event description.
        /// </summary>
        public static string NoEventTypeDescriptionError {
            get {
                return ResourceManager.GetString("NoEventTypeDescriptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No event title.
        /// </summary>
        public static string NoEventTypeTitleError {
            get {
                return ResourceManager.GetString("NoEventTypeTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No title.
        /// </summary>
        public static string NoTitleError {
            get {
                return ResourceManager.GetString("NoTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shifts:.
        /// </summary>
        public static string Shifts {
            get {
                return ResourceManager.GetString("Shifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TESTTESTESTTESTTESTEST.
        /// </summary>
        public static string TESTTESTESTTESTTESTEST {
            get {
                return ResourceManager.GetString("TESTTESTESTTESTTESTEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose theme.
        /// </summary>
        public static string ThemeChoose {
            get {
                return ResourceManager.GetString("ThemeChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark theme.
        /// </summary>
        public static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default theme.
        /// </summary>
        public static string ThemeDefault {
            get {
                return ResourceManager.GetString("ThemeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light theme.
        /// </summary>
        public static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rainbow theme.
        /// </summary>
        public static string ThemeRainbow {
            get {
                return ResourceManager.GetString("ThemeRainbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Title_Create {
            get {
                return ResourceManager.GetString("Title_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Title_Event {
            get {
                return ResourceManager.GetString("Title_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Title_Settings {
            get {
                return ResourceManager.GetString("Title_Settings", resourceCulture);
            }
        }
    }
}
